config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  resources :restaurants do
  resources :reviews, only: [:create, :new, :show, :index]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true
	validates :address, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zipcode, presence: true
	has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :rating, presence: true, numericality: {greater_than: 0, message: "Has to be 1 or greater", less_than: 6, message: "Has to be less than or equal to 5" }
	validates :review, presence: true
	belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = 'restaurant added.'
      redirect_to '/restaurants'
    else
      render :new
    end
  end


  def index
    @restaurants = Restaurant.all.order(created_at: :desc)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new    #why do we need this here?
    @reviews = @restaurant.reviews
  end





  protected
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :address, :city, :state, :zipcode, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id
    if @review.save
      flash[:notice] = "Review created successfully."
      redirect_to restaurant_path(@restaurant.id)
    else
      # render :template => 'restaurants/show'
      render :new
    end
  end

 protected
  def review_params
    params.require(:review).permit(:rating, :review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/home.html.erb
<h1>Welcome To Good Eats</h1>

<ul>
  <h3> Restaurants </h3>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

app/views/restaurants/index.html.erb
<div class="row">
  <div class="large-12">
    <h1>Restaurants</h1>

    <%- if !@restaurants.empty? -%>
      <table>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th></th>
        </tr>

        <%- @restaurants.each do |restaurant| -%>
          <tr>
            <td><%= restaurant.name %></td>
            <td>
              <%= link_to 'View details',
               restaurant_path(restaurant.id)%> 
            </td>

          </tr>
        <%- end -%>
      </table>

    <%- end -%>
    <tr>
      <%= link_to 'Add Restaurant',
        new_restaurant_path %>
    </tr>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="row">
  <%- if @restaurant.errors.present? -%>
    <div class="large-12 alert-box alert" data-alert>
      <ul>
        <%- @restaurant.errors.full_messages.each do |error| -%>
          <li><%= error %></li>
        <%- end -%>
      </ul>
    </div>
  <%- end -%>

  <div class="large-12">
    <h1>New Restaurant</h1>

    <%= form_for @restaurant do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :state %>
      <%= f.text_field :state %>

      <%= f.label :zipcode %>
      <%= f.text_field :zipcode %>

      <%= f.label :category %>
      <%= f.text_field :category %>



      <%= f.submit "Add Restaurant" %>
    <%- end -%>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="row">
 <div class="large-12">
   <h1>ANSWERS</h1>

     <table>
       <tr>
         <th>Restaurant Description</th>
         <th></th>
       </tr>

         <tr>
           <td><%= @restaurant.name %></td>
            <td><%= @restaurant.description %></td>
            <td><%= @restaurant.address %></td>
            <td><%= @restaurant.city %></td>
            <td><%= @restaurant.state %></td>
           <td><%= @restaurant.zipcode %></td>
            <td><%= @restaurant.category %></td>
           <td>

           </td>
         </tr>

     </table>


<ul>
  <h3> Reviews submitted by users </h3>
<% @reviews.each do |review| %> 
  <p>Rating: <%= review.rating %>, Review: <%= review.review %></p>
<%end%>
</ul>

<%= link_to 'Back', restaurants_path %>
<%= link_to 'Write a Review', new_restaurant_review_path(@restaurant.id) %>
 </div>
</div>

app/views/reviews/new.html.erb
<h2>Title: <%= @restaurant.name %></h2>

<h4>Post a Review</h4>

<%= form_for [@restaurant, @review] do |f| %>

 <p>
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </p>

  <p>
    <%= f.label :review %><br>
    <%= f.text_field :review %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>